### ISSUE TITLE
How to set Global Shipping Program and some setting for additional information

### ISSUE THREAD

**Issue by korcstar** [davidtsadler/ebay-sdk-examples#10]
I have tried to list item on UK eBay site by api
When I try to use Global shipping program, get error

![gps](https://cloud.githubusercontent.com/assets/13351126/8700732/37a75fe2-2b40-11e5-97d2-02c05548a650.png)

My code is following

$item->ShippingDetails = new Types\ShippingDetailsType();

$item->ShippingDetails->ShippingType = Enums\ShippingTypeCodeType::C_FLAT_DOMESTIC_CALCULATED_INTERNATIONAL;

//service setting for Royal Mail 1st Class & Free shipping

$shippingService = new Types\ShippingServiceOptionsType();
$shippingService->ShippingServicePriority = 1;
$shippingService->ShippingService = "UK_RoyalMailFirstClassStandard";
$shippingService->FreeShipping = true;

$item->ShippingDetails->ShippingServiceOptions[] = $shippingService;

//international setting for Global Shipping Programme, but not sure

$shippingService = new Types\InternationalShippingServiceOptionsType();
$shippingService->ShippingServicePriority = 2;
$shippingService->ShippingService = "InternationalPriorityShippingUK";        
        
$item->ShippingDetails->InternationalShippingServiceOption[] = $shippingService;

when i use this code, I get error

Postage service is not available.Postage service International Priority Shipping(50300) is not available.Invalid Postage Type.Postage Type is not supported by this site.

What is solution to set Global Shipping Programe?

Also I need help for some setting by api

How to set addtional return policicy details?
How to set additional payment instructions?

Thanks

**Comment by davidtsadler** [comment]
Issue continued at [eBay Developer forums](https://forums.developer.ebay.com/questions/12651/error-trying-to-use-global-shipping-program.html#comment-12701)
