### ISSUE TITLE
fatal error class DTS/ebaysdk/filetransfer/service/filetransferservice not found

### ISSUE THREAD

**Issue by xainbutt** [davidtsadler/ebay-sdk-examples#11]
i am not getting any filereferenceid and taskreferenceid....
![untitled](https://cloud.githubusercontent.com/assets/11776307/9244162/0761d74e-41b2-11e5-8a91-7084a9400428.jpg)

**Comment by davidtsadler** [comment]
It looks like you may be connecting to eBay's sandbox. From what I can tell there may be an issue with the sandbox in that it's not returning the FileReferenceID and TaskReferenceID fields.  Sadly the only thing I can recommend is that you may have better luck with using eBay's production server.
