### ISSUE TITLE
trading api issue in german site id

### ISSUE THREAD

**Issue by KalidassM** [davidtsadler/ebay-sdk-examples#14]
Hi David,

We have tried with this ebay examples, it works in US SITEID, but not working in GERMANY ( DE ) SITE ID,
Please help us to resolve this issue..

Thanks in advance,

**Comment by davidtsadler** [comment]
Hi,

Sorry I haven't got back to you sooner. I'll closing this issue as I will be replying on the [Google Group](https://groups.google.com/forum/?hl=en#!topic/ebay-sdk-php/7zdFKqBSjao)  instead.
