### ISSUE TITLE
Invalid property type: DTS\eBaySDK\Trading\Types\StoreCustomCategoryArrayType::CustomCategory expected <DTS\eBaySDK\Types\UnboundType>, got <DTS\eBaySDK\Trading\Types\StoreCustomCategoryType>

### ISSUE THREAD

**Issue by utsav** [davidtsadler/ebay-sdk-examples#15]
now i'm trying to store custom category to ebay store and i got this error

my code is like this.

`$siteId = Constants\SiteIds::US;

$config = config('configuration');

$service = new Services\TradingService(array(
    'apiVersion' => $config['tradingApiVersion'],
    'sandbox' => true,
    'siteId' => $siteId,
    'devId'  => $config['sandbox']['devId'],
    'appId'  => $config['sandbox']['appId'],
    'certId' => $config['sandbox']['certId']
));

$requests = new Types\SetStoreCategoriesRequestType();

$requests->RequesterCredentials = new Types\CustomSecurityHeaderType();
$requests->RequesterCredentials->eBayAuthToken = $config['sandbox']['userToken'];

$requests->Action = 'add';
$requests->ItemDestinationCategoryID = intval(1);
$requests->DestinationParentCategoryID = intval(0);

$storeCustomCategoryType = new Types\StoreCustomCategoryType();
$storeCustomCategoryType->Name = 'first 1 category testing';
$storeCustomCategoryType->Order = intval(1);

$storeCustomCategory = new Types\StoreCustomCategoryArrayType();
$storeCustomCategory->CustomCategory = $storeCustomCategoryType;

$StoreCategories[] = $storeCustomCategory;

$requests->StoreCategories = $StoreCategories;`

i can't understand this error please reply me with solution.

**Comment by utsav** [comment]
Ok, I solved. just set unbound from true to false [here](https://github.com/davidtsadler/ebay-sdk-trading/blob/a87c087f2ca1e286d01ca915cd70c5add6a1a5b0/src/DTS/eBaySDK/Trading/Types/StoreCustomCategoryArrayType.php#L32)

**Comment by davidtsadler** [comment]
There is no need to edit the code. You will need to set it back to 'true'. The [CustomCategory](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/SetStoreCategories.html#Request.StoreCategories.CustomCategory) field is known in the API as a [repeatable](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/simpleTypes.html#repeatable) field. This means that more than one value can be assigned to it. The SDK treats repeatable fields as arrays.

You can therefore assign values as follows.

```php
$storeCustomCategory->CustomCategory[] = $storeCustomCategoryType;
```

To be honest this is not explained in the SKD's docs or code.

You may also need to change `$requests->StoreCategories = $StoreCategories;` to `$requests->StoreCategories = $storeCustomCategory;` as the StoreCategories field is not repeatable and can only take one value.

**Comment by utsav** [comment]
i'm set unbound to true tryout about what you give and it work perfectly.
Thank You @davidtsadler .

**Comment by davidtsadler** [comment]
I've created some gists that show how to use the SDK using the [examples from the API docs](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/SetStoreCategories.html#samplebasic).

[Add eBay store category](https://gist.github.com/davidtsadler/cfe9ae0a732c624b3be2)
[Delete eBay store category](https://gist.github.com/davidtsadler/438f798e823c554546c5)
[Move eBay store category](https://gist.github.com/davidtsadler/ecabc146bc7ddbe5fe0a)
[Move eBay store category to top](https://gist.github.com/davidtsadler/33cddb98166967e81c26)
[Rename eBay store category](https://gist.github.com/davidtsadler/f623cb73df24649300ff)

**Comment by utsav** [comment]
i think you have to add this to this package in trading section.
but appreciate for your support. thank you.
