### ISSUE TITLE
No unity between classes

### ISSUE THREAD

**Issue by dinbrca** [davidtsadler/ebay-sdk-examples#17]
There is no unity between the classes of the responses.. for example: the response of SimpleItemType returns ItemID while the response of SearchItem returns itemId.. so if you want to create for example a product list from both SimpleItemType and SearchItem you need to do double work...

Thanks in advance,
Din.

**Comment by davidtsadler** [comment]
This is by design. The SDK uses the names as specified in the eBay WSDLs. Sadly eBay are not consistent in their naming. As an example, the Trading service uses the field Title but the Finding service uses title. At the moment I don't have plans to change the naming of properties.
