### ISSUE TITLE
Odd eBay Behavior

### ISSUE THREAD

**Issue by tpharaoh** [davidtsadler/ebay-sdk-examples#18]
I am sorry for posting this here, because I assume its not this git project, but I am looking for some ideas.

I built a simple product with your API. My Customer uploads a csv, then I give a publish button where they update what they want, then post. I am using: addFixedPriceItem.

They all get imported into eBay perfectly. It looks great.  Then, within 24 hours, ebay updates a handful of them, and changes 2 values:
Sale Start
Buy It Now Price

They tell me my API call did it... but it happened while no one was online... and it happens alot.

Customer does edit description and "markdowns" inside ebay itself. But, not at those times... those changes are still hours after any of us touch it. And, again, they claim its from our API calls.

**Comment by davidtsadler** [comment]
Sounds like someone or some application is calling ReviseItem. When viewing the item in eBay as a buyer there should be a list of revisions made to the it. If your app is only calling AddFixedPriceItem then it can't possibly be your code that is causing the revisions. 

If it's eBay support saying that it's your application then ask them for proof. Chances are that it's some support person on the end of the phone that doesn't have the authority to investigate the issue to any great depth and just wants to provide the seller with a simple answer.

**Comment by tpharaoh** [comment]
Your right. And my code doesn't implement any other feature except that.

They said I posted invalid data in my AddItem, which they then interpretted
and editedmy listing. But inmost cases its 12 hours later, so I don't see
how its related. It looks perfect all that time... untilthey edit. They
told me to buy a support ticket, so I guess I have to.
