### ISSUE TITLE
Some Trading examples not working for me

### ISSUE THREAD

**Issue by bryon-czoch** [davidtsadler/ebay-sdk-examples#21]
php 03-add-auction-item.php 
```
Error: Internal error to the application.
Internal error to the application.
```

**Comment by davidtsadler** [comment]
Looks it's a problem with the sandbox API that has been [reported](https://go.developer.ebay.com/sandbox-additem-families-calls-throwing-error-internal-error-application-intermittently). It's been resolved so the example should work.
