### ISSUE TITLE
how to add scheduled time in additem Trading API. 

### ISSUE THREAD

**Issue by taruncorcrm** [davidtsadler/ebay-sdk-examples#25]
Hello,

First of all thanks for great help on ebay API. But I am not able to find the way to add scheduled time. So can you please let me know the way to do so. 

I try $item->ScheduleTime=gmdate('Y-m-d\TH:i:s\Z'); But got error. Please let me know step for this. Thanks.

Thanks
Tarun

**Comment by davidtsadler** [comment]
Dates and times in the SDK are assigned using DateTime objects. For example,

```php
$item->ScheduleTime = new DateTime();
```
