### ISSUE TITLE
ShippingServiceDdetails

### ISSUE THREAD

**Issue by nilambaripatil** [davidtsadler/ebay-sdk-examples#29]
Hi, I am trying to upload the products and they are working except: 

Add Items Warning: (21916215) Your previously selected shipping service has been modified or removed. The proposed shipping service was therefore selected.
Your previously selected shipping service has been changed or removed. The proposed shipping service was therefore selected.

Add Items Warning: (21916711) The information on the return can not be used.
The information in the field on your return conditions Refund has been ignored (2121824)

Add Items Warning: (21916711) The information on the return can not be used.
The information in the field on your ReturnWithin return conditions has been ignored. (2121824)

shipping service is the most important, because it is not writing the correct details!

**Comment by nilambaripatil** [comment]
closed without reply or suggestion?

**Comment by davidtsadler** [comment]
Sadly I don't have an answer to why eBay are returning warnings. It seems from the messages that eBay can't use the information you have provided and have therefore selected a default value for the item.

Please in future use the [forum](https://groups.google.com/forum/#!forum/ebay-sdk-php) to raise personal issues with using the SDK as I want to keep the repository for tracking issues withe the code.
