### ISSUE TITLE
getOrders

### ISSUE THREAD

**Issue by Fabr9193** [davidtsadler/ebay-sdk-examples#32]
Hello everyone, 

I was trying to get all my purchases I did since this week on my sandbox ebay with the function getOrders but when I put

```
       $request->NumberOfDays = 30;
```

I have no results and when I add the filter 

```
        $request->OrderStatus = OrderStatusCodeType::C_ALL;

```

to be sure I take them all and still nothing .. but on my sbx ebay account I do have one purchase that I bought yesterday

Has anyone had the same problem ?

Thanks in advance, 

Fabricio

**Comment by davidtsadler** [comment]
Please use the [forum](https://groups.google.com/forum/#!forum/ebay-sdk-php) for personal issues with using the SDK. Ideally the repository should be for reporting bugs with the SDK.
