### ISSUE TITLE
Example of how to manipulate DetailLevel to get Item pictures

### ISSUE THREAD

**Issue by thiagomarini** [davidtsadler/ebay-sdk-examples#37]
Hi there!

It would be great if you could add an example of how to include items pictures when listing my Ebay selling.

https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/11-get-my-ebay-selling.php

Thanks

**Comment by davidtsadler** [comment]
DetailLevel can be specified as follows.

```php
$request->DetailLevel = ['ReturnAll', 'ItemReturnDescription']
```

It takes an array of values that can be found in the [eBay documentation](https://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/DetailLevelCodeType.html). The values you choose will be dependant upon what you want returned in the response. The documentation of the API calls will tell you for which value of DetailLevel a particular field will be returned for.
