### ISSUE TITLE
Ebay require EAN

### ISSUE THREAD

**Issue by IngegnereMatto** [davidtsadler/ebay-sdk-examples#38]
I'm using this sample:

https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/06-add-an-item-with-multiple-variations.php 

to add products with variations on ebay, but EAN is required. Is there a way to add EAN code to products with variations? I Have to specify EAN for each variations or only for the 'Main product' (All my variations have same EAN)?

**Comment by davidtsadler** [comment]
To add an EAN to the 'main product' use the [Item.ProductListingDetails.EAN](https://developer.ebay.com/DevZone/XML/docs/Reference/eBay/AddFixedPriceItem.html#Request.Item.ProductListingDetails.EAN) field.

```php
$productDetails = new Types\ProductListingDetailsType();
$productDetails->EAN = '...';
$item->ProductListingDetails = $productDetails;
```

To add an EAN to each variation use the [Variation.VariationProductListingDetails.EAN](https://developer.ebay.com/DevZone/XML/docs/Reference/eBay/AddFixedPriceItem.html#Request.Item.Variations.Variation.VariationProductListingDetails.EAN) field.

```php
$productDetails = new new Types\VariationProductListingDetails();
$productDetails->EAN = '...';
$variation->VariationProductListingDetails = $productDetails;
```

I've not tried the above code so you may have to adjust it in order for it to work.

Be aware that eBay will be changing how product identifiers are specified. The documentation has notes on the [current method](https://developer.ebay.com/devzone/guides/ebayfeatures/Development/Listing-AnItem.html#RequiredProductIdentifiersMandateOld) and the [future method](
https://developer.ebay.com/devzone/guides/ebayfeatures/Development/Listing-AnItem.html#RequiredProductIdentifiersMandate).
