### ISSUE TITLE
Error 500 with oAuth only on SDK > BulkDataExchange > createUploadJob

### ISSUE THREAD

**Issue by ajow** [davidtsadler/ebay-sdk-examples#39]
Hi David

I am getting the authentication error when using the oAuth token. Auth N Auth works fine so the sandbox credentials in config are good. Are there any configurations to be set in "SDK" class other than:

`$sdk = new Sdk([
 'credentials' => $this->config[$this->mode_creds]['credentials'],
 'authToken'   => $user_token,
'sandbox'     => $this->mode_flag,
]);`

Error:
`<errorMessage xmlns="http://www.ebay.com/marketplace/services"><error><errorId>11002</errorId><domain>Security</domain><severity>Error</severity><category>System</category><message>Authentication failed : Validation of the authentication token in API request failed.</message><subdomain>Authentication</subdomain><parameter name="Param1">Validation of the authentication token in API request failed.</parameter></error></errorMessage>`

Many thanks in advance.
Adam

**Comment by davidtsadler** [comment]
As far as I know you can't use the oAuth token with BulkDataExchange.  But you can use it in place of the Auth N Auth token for the Trading service through the [authorization](http://devbay.net/sdk/guides/guide/configuration.html#authorization) configuration option.
