### ISSUE TITLE
Ebay Category Issue

### ISSUE THREAD

**Issue by BillDavid07** [davidtsadler/ebay-sdk-examples#41]
Hi, I have question regarding the ebay categories. can i get a specific categories from ebay by using products categories came from amazon and attach to add item function in ebay?

I just want to post products to ebay using the products from amazon and my issue is i cant get specific categories by using the product categories from amazon.

Thanks & Regards.
JeromeD

**Comment by davidtsadler** [comment]
Are you wanting to automatically convert an Amazon category ID to an eBay category ID? If so then you won't be able to do it via the API.

You may be able to instead use [GetSuggestedCategories]( https://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetSuggestedCategories.html) You could pass the title of the Amazon product and let eBay suggest which categories on eBay to use.

**Comment by BillDavid07** [comment]
Ohh. i see. thanks david. will try it. :)
