### ISSUE TITLE
Error Status Code: 401  1001: Invalid access token

### ISSUE THREAD

**Issue by AntoninoPlatania** [davidtsadler/ebay-sdk-examples#42]
Goodmorning,

When i try "01-get-inventory-item.php" give me that error

How i can resolve?

Thank

**Comment by AntoninoPlatania** [comment]
i resolve,

now return 25710: We didn't find the entity you are requesting. Please verify the request 

how i can resolve that?

**Comment by rispeterson** [comment]
Hi @AntoninoPlatania, I am using 11-CreateorReplaceInventoryItem.php, and getting an error 401- Unauthorized' Client Exception. The Whole error goes like this : 

GuzzleHttp\Exception\ClientException: Client error: `PUT https://api.sandbox.ebay.com/sell/inventory/v1/inventory_item/123` resulted in a `401 Unauthorized` response: { "errors" : [ { "errorId" : 1001, "domain" : "OAuth", "category" : "REQUEST", "message" : "Invalid ac (truncated...) in C:\wamp64\www\Project1\vendor\ebay-sdk-php\GuzzleHttp\Exception\RequestException.php on line 113

How to solve this error

**Comment by waqar81** [comment]
my issue is also same i am using production token not sand box

**Comment by waqar81** [comment]
please help i am stuck with this
