### ISSUE TITLE
request: demonstrate listing with "Require immediate payment with Buy It Now" option

### ISSUE THREAD

**Issue by jlahijani** [davidtsadler/ebay-sdk-examples#43]
Would it be possible to update one of the existing examples (link this one; https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/04-add-fixed-price-item.php) demonstrating how to enable the "Require immediate payment with Buy It Now" option?  I'm not sure how to implement this with the API.  Or if you'd be able to put a snippet as a comment here that'd be great too.

![2017-08-06_15-49-31](https://user-images.githubusercontent.com/4558/29007752-e2363814-7abe-11e7-9655-781bae17e3aa.png)

Thank you.

**Comment by davidtsadler** [comment]
Have you tried to implement this yourself. If so do have any code to show that I could look at?

**Comment by jamiethompson** [comment]
I believe this would be as simple as `$item->AutoPay = true`

Source: https://developer.ebay.com/Devzone/XML/docs/Reference/eBay/AddFixedPriceItem.html
