### ISSUE TITLE
Exception: Call to undefined function DTS\eBaySDK\applyDebug()

### ISSUE THREAD

**Issue by Kaesar83** [davidtsadler/ebay-sdk-examples#44]
> An uncaught Exception was encountered
> Type: Error
> Message: Call to undefined function DTS\eBaySDK\applyDebug()
> Filename: >C:\xampp\htdocs\test\application\third_party\ebaysdk\DTS\eBaySDK\ConfigurationResolver.php
> Line Number: 59
> Backtrace:
> File: >C:\xampp\htdocs\test\application\third_party\ebaysdk\DTS\eBaySDK\Services\BaseRestService.php
> Line: 53
> Function: resolve
>
>File: >C:\xampp\htdocs\test\application\third_party\ebaysdk\DTS\eBaySDK\Inventory\Services\InventoryBaseService.php
>Line: 32
> Function: __construct
>
>File: >C:\xampp\htdocs\test\application\third_party\ebaysdk\DTS\eBaySDK\Inventory\Services\InventoryService.php
>Line: 314
>Function: __construct
>
>File: C:\xampp\htdocs\test\application\models\EbayModel.php
>Line: 680
>Function: __construct
>
>File: C:\xampp\htdocs\test\application\controllers\Ebay.php
>Line: 32
>Function: loadOnEbay

I have the error above.
This happens when it's called the code below, as explained in the **Create or replace inventory item** example

`/**
		 * Create the service object.
		 */
		$service = new DTS\eBaySDK\Inventory\Services\InventoryService([
				'authorization'    => $ebayConfig['sandbox']['oauthUserToken'],
				'requestLanguage'  => 'en-US',
				'responseLanguage' => 'en-US',
				'sandbox'          => true
				]);`

Could you help me?

Thanks in advance

**Comment by Kaesar83** [comment]
OK, I solved it. :)

Missed including ebay-sdk-php-autoloader.php file.

Thank you

**Comment by davidtsadler** [comment]
Thank you for the update. Was going to look into this today so you've saved me some time :)
