### ISSUE TITLE
Cannot read credentials

### ISSUE THREAD

**Issue by Kaesar83** [davidtsadler/ebay-sdk-examples#45]
> An uncaught Exception was encountered
> Type: InvalidArgumentException
> Message: Cannot read credentials from C:\Users\Cesare/.ebay_sdk/credentials
>
>Filename: >C:\xampp\htdocs\test\application\third_party\ebaysdk\DTS\eBaySDK\Credentials\CredentialsProvider.php
>Line Number: 132
>
>Backtrace:

Hi, 
I have the error above when I try to use the code in **03-refresh-user-token.php**

Could you help me?

Thank you in advance

**Comment by oralunal** [comment]
Probably the credentials you provided are missing.
