### ISSUE TITLE
Where i can obtain <AUTHORIZATION_CODE>?

### ISSUE THREAD

**Issue by nolka** [davidtsadler/ebay-sdk-examples#48]
Hi!
This code used here: https://github.com/davidtsadler/ebay-sdk-examples/blob/76376b3e804829967a3385f8960ae94bd0de8928/oauth-tokens/02-get-user-token.php#L50
I can't understand, where i can obtain it? :(

**Comment by davidtsadler** [comment]
The authorization code is a value that is returned from eBay after the user had logged into their account and granted permission for your application. Read the documentation https://developer.ebay.com/api-docs/static/oauth-user-token.html

**Comment by shwetatrivedi-sdd** [comment]
Hi David , I have the same issue 
 https://developer.ebay.com/api-docs/static/oauth-user-token.html
I have the same issue - this 

ebay-sdk-examples/oauth-tokens/02-get-user-token.php

 $request->code = '<AUTHORIZATION CODE>';
