### ISSUE TITLE
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST https://svcs.ebay.com/services/sellerinventory/v1/BundleManagementService` resulted in a `500 Internal Server Error` response:

### ISSUE THREAD

**Issue by marcopolo88** [davidtsadler/ebay-sdk-examples#51]
is this part of the API deprecated?

- no info or help on how to create bundles via ebay webinterface anywhere

- here the API example does not work (double checked production credentials, reissued as well)
`/**
 * Create the service object.
 */
$service = new Services\RelatedItemsManagementService([
    'credentials' => $config['production']['credentials'],
    'authToken'   => $config['production']['authToken'],
    'globalId'    => Constants\GlobalIds::DE,
    'sandbox'  => false
]);`

> Fatal error: Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST https://svcs.ebay.com/services/sellerinventory/v1/BundleManagementService` resulted in a `500 Internal Server Error` response:

- searching for the API, Top 3 results in serp are dead
https://www.google.com/search?q=Related+Items+Management+API

**Comment by tmaly1980** [comment]
Any luck with this? I am actually coming across a 500 ISE for EVERYTHING.
