### ISSUE TITLE
error 01-search-for-items.php on line 42

### ISSUE THREAD

**Issue by rodriayala** [davidtsadler/ebay-sdk-examples#55]
Hi i try to use that app and i have that problem:

Fatal error: Class 'DTS\eBaySDK\Browse\Services\BrowseService' not found in /var/www/html/ebay-sdk-examples/browse/01-search-for-items.php on line 42

Any idea what it could be?

thanks.

**Comment by rbur0425** [comment]
You need to autoload the package. Are you using composer? 

Do you have this at top of code? 


```
/**
 * Include the SDK by using the autoloader from Composer.
 */
require __DIR__.'/../vendor/autoload.php';
/**
 * Include the configuration values.
 *
 * Ensure that you have edited the configuration.php file
 * to include your application keys.
 */
$config = require __DIR__.'/../configuration.php';

```
