### ISSUE TITLE
Issue occured when  try to get Auth token in EBAY API

### ISSUE THREAD

**Issue by ssrgspdkt** [davidtsadler/ebay-sdk-examples#58]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\apis\ebay-sdk-examples\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp\htdocs\apis\ebay-sdk-examples\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\apis\ebay-sdk-examples\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\apis\ebay-sdk-examples\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(180): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(Guz in C:\xampp\htdocs\apis\ebay-sdk-examples\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by oralunal** [comment]
This error is occuring in your server. You should check your local SSL certificates for CURL. Google for "cURL error 60: SSL certificate problem: unable to get local issuer certificate"
