### ISSUE TITLE
Getting sold / available quantity

### ISSUE THREAD

**Issue by 3zzy** [davidtsadler/ebay-sdk-examples#6]
I need to get sold/available quantity for a particular product and it seems getSingleItem is the only option: http://developer.ebay.com/devzone/shopping/docs/callref/GetSingleItem.html

I'm changing the field selector to:

`$request->IncludeSelector = 'QuantitySold';`

.. but it doesn't return anything at all. What am I doing wrong?

**Comment by davidtsadler** [comment]
You need to pass `Details`.

`$request->IncludeSelector = 'Details';`. 

I'll update the [GetSingleItem](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/shopping/02-get-single-item.php) example so that it displays the Quantity.
