### ISSUE TITLE
How to use this API GetCompatibilitySearchValuesRequest filter

### ISSUE THREAD

**Issue by yashangqingsong** [davidtsadler/ebay-sdk-examples#61]
dear @davidtsadler

ebay-sdk-examples-master/product_metadata/02-get-compatibility-search-values.php

How to add the parameters of the filter, can you give an example：
/**

Create the request object.
*/
$request = new Types\GetCompatibilitySearchValuesRequest();
$request->categoryId = '174090';
$request->propertyName = 'Model';
$request->propertyFilter = [????];//eg. filter Car Make => BMW
$request->listFormatOnly = true;
I wrote the code like this :
$request->propertyFilter = [
'propertyFilter' => new Types\PropertyValue(
[
'propertyName' => new Types\Value(
new Types\StringValue(['propertyFilter' => 'BMW'])
)
]
)
];

But it's always wrong。

**Comment by andrewtch** [comment]
@yashangqingsong , @davidtsadler 

Should be smth like this, get all Audi models:

```
        $request = new GetCompatibilitySearchValuesRequest();
        $request->categoryId = '33567';

        $filter = new PropertyValue();
        $filter->propertyName = 'Make';
        $value = new Value();
        $value->text = new StringValue(['value' => 'Audi']);
        $filter->value[] = $value;

        $request->propertyFilter[] = $filter;
        $request->propertyName = 'Model';
        $request->listFormatOnly = true;
```
