### ISSUE TITLE
Auth token is invalid     php trading/13-get-store.php

### ISSUE THREAD

**Issue by yanggg1133** [davidtsadler/ebay-sdk-examples#62]
php trading/13-get-store.php
`DTS\eBaySDK\Trading\Types\GetStoreRequestType Object
(
    [values:DTS\eBaySDK\Types\BaseType:private] => Array
        (
            [RequesterCredentials] => DTS\eBaySDK\Trading\Types\CustomSecurityHeaderType Object
                (
                    [values:DTS\eBaySDK\Types\BaseType:private] => Array
                        (
                            [eBayAuthToken] => v^1.1#i^1#r^0#I^3#f^0#p^1#t^H4sIAAAAAAAAAOVXb2wURRTvtdcSRBQB+euHY5GIkN2b3ett91buyhUo1BZaubMtECz7Z7Zse7d77sxyPRRtLgQEY0xjQCWklGgIQQLBGBNEPhg0BhIg/kEFE/ziByDywRjEgFFn945yVwk9oEQSL7nczcx7b97vN+/Nmwd6q0bP2bRk09WxnlHlA72gt9zjYceA0VWVcx+pKJ9WWQYKBDwDvU/2erMVF+YhKZlIicshSpkGgr6eZMJAojsZpmzLEE0J6Ug0pCREIlbEWHRpk8gxQExZJjYVM0H5GhaGKZaXtVAgWM2GhBouqNaQWeOGzbgZpnhZ5RSghWRYA1W+RiLrCNmwwUBYMnCY4gAr0ICnueo44EXAipzACJywkvK1QgvppkFEGEBFXHdFV9cq8PX2rkoIQQsTI1SkIVofa442LFy0LD7PX2ArkuchhiVso+LRAlOFvlYpYcPbb4NcaTFmKwpEiPJHcjsUGxWjN5y5C/ddqmUVqBzgORVCwLKBEWGy3rSSEr69G86MrtKaKypCA+s4MxyhhAy5Cyo4P1pGTDQs9Dk/z9lSQtd0aIWpRXXRFdGWFiqSkYxO50unnT86NulYXTvNcYoiE7CQhrwWDNVowfxGOWt5lofstMA0VN3hDPmWmbgOEq9hMTdBMVjADRFqNpqtqIYdjwrlhBscstxK50xzh2jjtYZzrDBJiPC5w+FPYFAbY0uXbQwHLQxdcCkKU1IqpavU0EU3FPPR04PC1FqMU6Lfn06nmXSAMa1OPwcA629f2hRT1sIkyTUi6+S6K68Pr0DrLhQFEk2kiziTIr70kFAlDhidVCQAAgE+lOe92K3I0Nl/TRRg9hcnxEgCqpwZCkcUGJ5TleHZG7JpIPUr/jB5SlDJ2UrG6IUwlJgbRC4sxOQktXxUBQ4wKCBmmVD2l0dUjTaDmo8jSrkXSFUJaVkPB/SpRSQz2mmCnYYiZ0JTMyAT9iwW6pLZKFM3V2hoxjMJEgP6XG/i2hIgfq/QTp5PqdA3VsIGJESumME+GMYib9pkSuNmeqw/XaV4qQX7YzTKcNESZuq6S6lKykkxBhSKKopavk0pAAKF2FvFxUW8HuRvd0kDqp8g9UrBLEOei6mqvPjIufQesUxoLItC3yMmGanXIVN7uhQZIfW2YiAa1W9p6YGMFC9d8UqVuiUhI6obHjQUNWdPt7s+Xs8BXgLuNbwg8WcjbIhQSiIgj3hGuBe67xzP29he8c3hIT4dKvpDt4V/mLm7xImfths56jIOs5TPpEUANodi54uqrieW/FwxQiFzGDJEOVzR5GlzQG6Z0G6WEsyHTDTErSrfIqz6rpl2r/LGgvB1aDKYMN5ugKdkxBtwmeuLlSyT46eSwrkA6mGvCAJa8KMPPmqped5J14ZvW5OaHqvy/P/uDqrmOxhy5426bvB2MHhTyeyjJv1lNWf6X/maq2A183GSepK5PLW41R+7+YffKHH/ed+n3MT0rLiSMVx7NbF1/qop+KHlvftfH6L7/WNn255jPU14N2zDhtXVz83uNnOw5/f/DNV/umDLz8W9v4gxfb/zh07Vp23JwthzrnHdk8a/fnV1uDb8w9sfj9r7Ytv3L+xW796IeV0pklG+CnqV1vddEfTf1GWB9/l98RPLMzvbGj76Xrq7VxewLppZ+cbtw2tW3CYwfQ5q7xLQevbZ/2yp6dledWxc5uiEdXTjS3zfp2a+OkuEhvvT7j9ZntH6/bu6Z/X62wcff8y90nJvSWnRfgO2d/3uHh+95u5C7+VT+x6/R+47VTtdtji579boXVP+r4C3vn547xH5et2/X4DwAA
                        )

                    [attachment:DTS\eBaySDK\Types\BaseType:private] => Array
                        (
                            [data] =>
                            [mimeType] =>
                        )

                )

        )

    [attachment:DTS\eBaySDK\Types\BaseType:private] => Array
        (
            [data] =>
            [mimeType] =>
        )

)`
Error: Auth token is invalid.
Validation of the authentication token in API request failed.

**Comment by mburton3969** [comment]
@davidtsadler I am having a similar issue when attempting to run this file [ebay-sdk-examples/trading/04-add-fixed-price-item.php]

I have narrowed down the issue to this section of code:
```
/**
 * An user token is required when using the Trading service.
 */
$request->RequesterCredentials = new Types\CustomSecurityHeaderType();
$request->RequesterCredentials->eBayAuthToken = $config['production']['authToken'];
```

When I run this file, I receive the following error response [Both in sandbox and production]:
`Error: Auth token is invalid. Validation of the authentication token in API request failed.`

When I run the same authToken through the "API Explorer" tool on Ebay's developer site, I have no issues and no error response which leads me to believe it is an issue with the code above...

Question is: Is this an issue with the code in the example file provided? Or is there an issue authenticating an access token via the API on Ebay's side?

Also, should this line of code:
`$request->RequesterCredentials->eBayAuthToken = $config['production']['authToken'];`
be this:
`$request->RequesterCredentials->eBayAuthToken = $config['production']['oauthUserToken'];`
(as developer's docs on Ebay suggest a User Token is required for this type of API call... I've tried both ways with the same error response)

Any point of help would be greatly appreciated!!

**Comment by dawguk** [comment]
I have found that Auth'n'Auth tokens are working fine, when provided in the authToken value of the config - you can generate one of those in your developer account on ebay. I haven't managed to get an OAuth token working with this software yet (and I've been trying for two hours ...)

**Comment by mburton3969** [comment]
@dawguk I finally figured out why OAuth was not working. I made the following modifications to the code:

Added 3 items to the TradingService Configuration:
```PHP
/**
 * Create the service object.
 */
$service = new Services\TradingService([
    'credentials' => $config['sandbox']['credentials'],
    'authorization' => $config['sandbox']['oauthUserToken'],//Added This
    'requestLanguage'  => 'en-US',//Added This
    'responseLanguage' => 'en-US',//Added This
    'sandbox'     => $env_mode_val,
    'siteId'      => $siteId
]);
```
I also removed (or comment out) the following code:
```PHP
/**
 * An user token is required when using the Trading service.
 */
//$request->RequesterCredentials = new Types\CustomSecurityHeaderType();
//$request->RequesterCredentials->eBayAuthToken = $config[$env_mode]['authToken'];
```

The SDK seems to need the Auth Token sent through the Service setup rather than doing it through the RequesterCredentials method. Not exactly sure why, but these changes worked perfectly for me. 

I opened a pull request ***[Corrected oAuth Access Method]*** where i corrected all the example files in the Trading folder, so you can look at them if you would like.

Hope this helps!

**Comment by KiloooNL** [comment]
> 
> 
> @dawguk I finally figured out why OAuth was not working. I made the following modifications to the code:
> 
> Added 3 items to the TradingService Configuration:
> 
> ```
> /**
>  * Create the service object.
>  */
> $service = new Services\TradingService([
>     'credentials' => $config['sandbox']['credentials'],
>     'authorization' => $config['sandbox']['oauthUserToken'],//Added This
>     'requestLanguage'  => 'en-US',//Added This
>     'responseLanguage' => 'en-US',//Added This
>     'sandbox'     => $env_mode_val,
>     'siteId'      => $siteId
> ]);
> ```
> 
> I also removed (or comment out) the following code:
> 
> ```
> /**
>  * An user token is required when using the Trading service.
>  */
> //$request->RequesterCredentials = new Types\CustomSecurityHeaderType();
> //$request->RequesterCredentials->eBayAuthToken = $config[$env_mode]['authToken'];
> ```
> 
> The SDK seems to need the Auth Token sent through the Service setup rather than doing it through the RequesterCredentials method. Not exactly sure why, but these changes worked perfectly for me.
> 
> I opened a pull request _**[Corrected oAuth Access Method]**_ where i corrected all the example files in the Trading folder, so you can look at them if you would like.
> 
> Hope this helps!

When using your method, I'm getting "Error: Invalid IAF token. IAF token supplied is invalid. "
Is the header missing  X-EBAY-API-IAF-TOKEN using this method or something?
