### ISSUE TITLE
How to get user store details by using access token?

### ISSUE THREAD

**Issue by buddyy93** [davidtsadler/ebay-sdk-examples#69]
I'm trying to get user store details, like the store name, desciption and such..
is it possible to do it ? if so please anyone tell me how, thank you.

**Comment by kernio** [comment]
The best for you will take a look into the developer documentation of ebay.
Here you can find a link for Trading Api reference— https://developer.ebay.com/Devzone/XML/docs/Reference/eBay/index.html
As soon as you find the corresponding api, you can find a related code in this library.

(answer to your question — https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/13-get-store.php)
