### ISSUE TITLE
how to get seller's products ?

### ISSUE THREAD

**Issue by buddyy93** [davidtsadler/ebay-sdk-examples#70]
i've been looking in the examples, but i haven't anything that shows how to get products for specific sellers by using access token..
please someone help, thank you

**Comment by kernio** [comment]
The best for you will take a look into the developer documentation of ebay.
Here you can find a link for Trading Api reference— https://developer.ebay.com/Devzone/XML/docs/Reference/eBay/index.html
As soon as you find the corresponding api, you can find a related code in this library. 

(and answering to your question, here example you are looking for — https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/11-get-my-ebay-selling.php)

**Comment by buddyy93** [comment]
@kernio hi, thank you, it's working! :)
