### ISSUE TITLE
I'm getting "Server error: `POST https://svcs.ebay.com/services/search/FindingService/v1` resulted in a `500 Internal Server Error`"

### ISSUE THREAD

**Issue by cservit** [davidtsadler/ebay-sdk-examples#71]
Hi,
i'm getting a http 500 error. I did not changed anything, but till saturday i'm getting this error on different servers. I've also recreated my certifiate ID, but nothing changes.

Here is a sample code (it's very similar to the samples):

`require_once DIRPATH . '/lib/vendor/autoload.php';

$service = new  DTS\eBaySDK\Finding\Services\FindingService( [
		'apiVersion' => '1.13.0',
		'globalId'   => $globalId,

		'credentials' => [
				'appId'  => $appId,
				'certId' => $certId,
				'devId'  => $devId
		]
] );

$request           = new DTS\eBaySDK\Finding\Types\FindItemsByKeywordsRequest();
$request->keywords = 'Harry Potter';

// Ask for the first 25 items.
$request->paginationInput                 = new DTS\eBaySDK\Finding\Types\PaginationInput();
$request->paginationInput->entriesPerPage = 1;
$request->paginationInput->pageNumber     = 1;

// Send the request.
$response = $service->findItemsByKeywords( $request );`

I't would be great, if someone has an idea or can test the sample above....

**Comment by inzamam-idrees** [comment]
I face the same problem but could not find any solution for this. Please help us

**Comment by firstroad** [comment]
Having the same issue, with FileTransfer downloadFile call, could someone else confirm?

**Comment by cservit** [comment]
Hi,
i found the solution for this issue. ebay has implemented a limitation of requests. If this daily limit is reached, you are getting this exception. 

https://developer.ebay.com/support/api-call-limits

You can create a compatible check: https://developer.ebay.com/support/app-check

I've submitted ths app check and was approved. The error is gone.

**Comment by cservit** [comment]
> didn't work for me, today with no requests, just got the tokens and then error again

Yeah, the api blocking is not just one day. A customer has testet it and told me the blocktime is arbitrary. 
That issue is not a problem of the php sdk. Just create a ticket and ask the ebay support. My issue was confirmed by them.
