### ISSUE TITLE
Error Status Code: 401 1001: Invalid access token new issue

### ISSUE THREAD

**Issue by waqar81** [davidtsadler/ebay-sdk-examples#81]
Status Code: 401 1001: Invalid access token Invalid access token. Check the value of the Authorization HTTP request header.

$service = new Services\InventoryService([
    'authorization'    => $config['sandbox']['oauthUserToken'],
    'requestLanguage'  => 'en-US',
    'responseLanguage' => 'en-US',
    'sandbox'          => true
]);

**Comment by sahakavatar** [comment]
+++++++++++++++++++++++++++++++++
