### ISSUE TITLE
How can I get the tracking number of an Order I placed?

### ISSUE THREAD

**Issue by elkpodemiami** [davidtsadler/ebay-sdk-examples#85]
Hello, I've been using the "Types\GetOrdersRequestType" to get orders that the company I work for purchases, before it used to return the tracking number associated with the specific order so I could add it on my company's Db to avoid people from going to ebay and search for trackings manually, looks like it no longer returns this information and I can't find anywhere if the SDKs changed in regards to this.

Please assist.

**Comment by amirvenus** [comment]
Do you mind sharing your code? 

I am struggling to get a single order based on its order id. 

Thanks
