### ISSUE TITLE
Error: System currently not available BUT offer gets created

### ISSUE THREAD

**Issue by Christian1998** [davidtsadler/ebay-sdk-examples#88]
Hi friends,
im currently coding an webinterface for eBay and Amazonmanagement. Tried the examples-all worked nearby like a charm. So far so good...
Tried the example today and get the error that the system currently not available is... After this i get an email that my product was successful created. It worked yesterday without problems...

```
Christians-iMac:~ neolium$ php /Applications/XAMPP/xamppfiles/htdocs/ebay/trading/05-add-an-item-with-item-specifics.php 
Error: Das System ist vorübergehend nicht verfügbar. Bitte versuchen Sie erneut, Ihr Angebot einzustellen.
```

Anyone knows a solution?
Thanks

**Comment by Christian1998** [comment]
5 days are gone and nobody has the same problem?
I'm confused and still have the problem...
@davidtsadler @richbradshaw @misterakko @JProof

**Comment by Christian1998** [comment]
Yea 20 days are over - nobody seems to be interested in it or is able to fix the issue on the backend of ebay. So just fck ebay

**Comment by JProof** [comment]
Perhaps you can try 2lern develop ;-)

**Comment by Christian1998** [comment]
> Perhaps you can try 2lern develop ;-)
Das wirds sein ;-)
